### ISSUE TITLE
IPPrefix from Mask

### ISSUE THREAD

**Issue by terinjokes** [inetaf/netaddr#133]
Right now there are four ways to construct an `IPPrefix`:

1. Parsing an string with an IP represented in CIDR notation: `netaddr.ParseIPPrefix("127.0.0.1/8")`
2. Providing the significant bits to an `IP` struct: `netaddr.IPv4(127, 0, 0, 1).Prefix(8)`
3. Working with `IPRange`: `netaddr.ParseRange("127.0.0.0-127.0.0.255").Prefix()` (ignoring error returns)
4. Working with `IPSet`: `ipset.Prefixes()`

I'm working with a kernel API that returns the IP mask itself[^1]. I can turn this into an IPPrefix by first using `net.IPMask` and calling `Size`.

```go
func main() {
	var mask [4]byte
	netmask := make(net.IPMask, net.IPv4len)

	mask = getKernelMask()
	copy(netmask, mask[:])

	bits, _ := netmask.Size()
	ip, _ := netaddr.IPv4(127, 0, 0, 1).Prefix(uint8(bits))

	fmt.Printf("IPPrefix: %s\n", ip)
}
```

Would there be any interest in allowing an `IPPrefix` to be constructed either directly from a netmask representation, or alternatively from a `net.IPMask`?

[^1]: The kernel API returns the netmask for IPv4. For IPv6 they switched to returning the significant bits instead.

**Comment by mdlayher** [comment]
Can you provide a couple of proposed function signatures? Are you just trying to do this all in one operation?

**Comment by terinjokes** [comment]
This would primarily be a convince to avoid needing to converting masks to significant bits and the error checking for valid lengths and bit patterns at each stage.

Some ideas:

* `func (ip IP) Netmask(mask []byte) (IPPrefix, error)`
  This is the straight-forward answer for the use case I have. The created `IPPrefix` would be usable with `IPRange` and `IPSet`, but not `IPSet`'s `RemoveFreePrefix`.
* `func Netmask(ip IP, mask []byte) (IPPrefix, error)`
  Construct an IPPrefix from an existing IP and the netmask. Move the previous idea to `IPPrefix` instead.
* `func Netmask(mask []byte) uint8`
  A helper function that correctly does the conversion from masks to significant bits correctly for IPv4 and IPv6, and could be passed to `ip.Prefix` and `ipset.RemoveFreePrefix`.
* Any of the above with `[]byte` swapped out for `net.IPMask`
  Users would need to work directly with a stdlib IP struct to create the `net.IPMask`

I'm open to other suggestions.

**Comment by mdlayher** [comment]
Cool cool. I don't have strong opinions as every system I currently use netaddr with speaks CIDR natively. It is important to keep in mind that stdlib net.IPMask supports non-contiguous subnet masks (yuck) and netaddr explicitly does not. So any API that converted from bytes/net.IPMask would need error checks for that case.

**Comment by mdlayher** [comment]
I think my current preference is `func (ip IP) Netmask(mask []byte) (IPPrefix, error)` with a copy of the internal check for non-contiguous subnet masks that `FromStdIPNet` does. You could also potentially leverage that call in your code?

**Comment by terinjokes** [comment]
>  I don't have strong opinions as every system I currently use netaddr with speaks CIDR natively.

Just wait. :stuck_out_tongue: 

> You could also potentially leverage that call in your code?

If there's no immediate rejections I'll work on throwing up a changeset to review.

**Comment by mdlayher** [comment]
Any more thoughts here?

**Comment by terinjokes** [comment]
I went on vacation. 😂
