### ISSUE TITLE
Proposal: make IPSet immutable, add IPSetBuilder

### ISSUE THREAD

**Issue by danderson** [inetaf/netaddr#138]
Trying to use IPSet in code, it's annoying that it's mutable. It means I have to either defensively copy, or convert into Ranges and reimplement Contains.

Separately, IPSet.ContainsFunc has a todo about maybe using a more efficient representation for pure matching, once the IPSet is constructed.

Empirically, so far all my uses of IPSet have a "build" phase where I add/remove prefixes, followed by a "use" phase where I want read-only use.

How about making a mutable IPSetBuilder, which produces an immutable IPSet? Then we have the freedom to vary IPSet's representation for efficient read ops; IPSet can behave more like the other types in netaddr (no risk of surprise mutations); and we're more explicit about isolating the more expensive operations into a "build" phase. We can have IPSet.ToBuilder(), for the cases where you have an IPSet you like but just want to tweak a bit.

/cc @bradfitz @josharian @mdlayher thoughts?

**Comment by danderson** [comment]
Current use that motivated this issue is adjusting tailscale's wgengine/filter to take a set of local IPs rather than a list of prefixes, because I need to be able to efficiently punch out some LAN ranges from 0/0. Semantically, I want an IPSet that I can Contains() against, but its mutability means that I'm instead taking in a safer []IPRange, and implementing my own Contains.

**Comment by mdlayher** [comment]
Seems reasonable to me. I haven't had to use this type in my own code yet.

**Comment by bradfitz** [comment]
Agreed. Let's do it.

**Comment by josharian** [comment]
Works for me. (Familiar from old Obj-C world, in which almost all data types have mutable and immutable variants.)

I don't think we need IPSet.ToBuilder():

```go
sb := new(IPSetBuilder)
sb.AddSet(oldset)
// do other things
newset := sb.Set()
```

**Comment by danderson** [comment]
Implementing.

One minor ugliness right now is RemoveFreePrefix, which is a mutating method meant for steady-state use. Given how it gets used, the caller would basically keep an IPSetBuilder around for ever and pull out prefixes periodically. That's probably fine, but the "Builder" name is a bit weird to have as a long-lived object.

**Comment by josharian** [comment]
> One minor ugliness right now is RemoveFreePrefix, which is a mutating method meant for steady-state use. Given how it gets used, the caller would basically keep an IPSetBuilder around for ever and pull out prefixes periodically.

Another API option is for it to return a new IPSet that is the original set minus the removed prefix:

```go
func (s *IPSet) RemoveFreePrefix() (smallerSet *IPSet, p IPPrefix, ok bool)
```

I don't know whether there are compelling performance reasons to do it the other way, but I personally think this API is nicer.
