### ISSUE TITLE
Clone submodule using HTTPS

### ISSUE THREAD

**Issue by elmeyer** [inetaf/netaddr#155]
When cloning this repository with `--recursive` and without a Github SSH key, cloning fails due to the corpus submodule URI using SSH.

Some people (like me) are unfortunately still stuck using `dep` for their projects for various reasons, even though it's been deprecated a long time ago. `dep` defaults to cloning recursively, and will therefore always fail when "inet.af/netaddr" is imported.

If you have other suggestions on how to circumvent this issue (except "just switch to Go modules"), please let me know; otherwise, I have prepared a PR.

**Comment by josharian** [comment]
For future reference, one way to fix this is to use git's insteadOf. See e.g. https://gist.github.com/Kovrinic/ea5e7123ab5c97d451804ea222ecd78a.

**Comment by elmeyer** [comment]
@josharian Thank you, very useful!
