### ISSUE TITLE
remove IPPort.WithIP, IPPort.WithPort?

### ISSUE THREAD

**Issue by josharian** [inetaf/netaddr#191]
These were useful as shims while updating Tailscale to use the opaque IPPort. They're a bit ugly, though. Should we remove them prior to upstreaming?

**Comment by jzelinskie** [comment]
Did you just replace those calls with `netaddr.IPPortFrom()`?

**Comment by josharian** [comment]
> Did you just replace those calls with netaddr.IPPortFrom()?

I haven't done it yet. The fix would be a combination of two things. In some places, explicitly tracking an IP and a port. In others, replacing with IPPortFrom.

**Comment by josharian** [comment]
Upstreaming of IPPort (as AddrPort) is complete; these got cut.
