### ISSUE TITLE
add IP.Unspecified?

### ISSUE THREAD

**Issue by bradfitz** [inetaf/netaddr#195]
I was just porting some code from net.IP to netaddr.IP and discovered we don't have netaddr.IP.IsUnspecified like std.

Add it?

/cc @danderson @josharian @mdlayher

**Comment by mdlayher** [comment]
+1 from me, would save me a couple of `ip == net.IPv6Unspecified()` anyway.

**Comment by danderson** [comment]
Sure. Make sure the docs make it very clear how IsUnspecified and IsZero differ.
