### ISSUE TITLE
inet.af or inetaf

### ISSUE THREAD

**Issue by mclaut** [inetaf/netaddr#200]
Hi

I make go get -u github.com/inetaf/netaddr, and receive:
>go get -u github.com/inetaf/netaddr
go get: github.com/inetaf/netaddr@none updating to
        github.com/inetaf/netaddr@v0.0.0-20210707202901-70468d781e6c: parsing go.mod:
        module declares its path as: inet.af/netaddr
                but was required as: github.com/inetaf/netaddr

**Comment by mdlayher** [comment]
The module path is `inet.af/netaddr`, not the GitHub URL. See also https://pkg.go.dev/inet.af/netaddr. Closing.
