### ISSUE TITLE
netaddr: implement MarshalText, UnmarshalText for IPPort

### ISSUE THREAD

**Issue by mdlayher** [inetaf/netaddr#26]
netaddr.IP implements these methods for JSON conversions and such. I would argue that we should do the same for IPPort (ex: `"192.168.1.1:80"`) and IPPrefix (ex: `"2001:db8::/64"`).

**Comment by bradfitz** [comment]
Retitled. Looks like only IPPort remains, which doesn't even have `ParseIPPort(string)` (or `IPPort.String`)

**Comment by bradfitz** [comment]
Retitled again. ParseIPPort and String are done.

**Comment by danderson** [comment]
Done in 1fa1b5efbb1485438de66c2d05bb15067a1b05c3 , forgot to cross-link to issue.
