### ISSUE TITLE
proposal: add additional methods to support IPv6 expansion

### ISSUE THREAD

**Issue by jimmystewpot** [inetaf/netaddr#51]
Hi There,

I saw this package and thought that it overlapped with some work that I have been doing recently. With IPv6 the addresses are usually shortened, have you thought about adding a feature where you can print out the expanded IPv6 format?

Example
```
ip, _ := netaddr.ParseIP("2404:6800:4006:809::200e")
ip.As16ExpandedShort() // 2404:6800:4006:0809:0:0:0:200e
ip.As16ExpandedLong() // 2.4.0.4.6.8.0.0.4.0.0.6.0.8.0.9.0.0.0.0.0.0.0.0.0.0.0.0.2.0.0.e
```

The use case for this is the automatic creation of DNS IPv6 PTR records however I am sure that there are other use cases. Is this something that you have thought about as an addition to this package or do you see it as out of scope?

If it is in scope I am happy to do the work and provide you with a PR, I just wanted to check if its aligned with where you want to take your package.

**Comment by mdlayher** [comment]
I've seen some systems that don't handle the compressed format properly and think it'd be reasonable to add the first method to expand `::`, but I would also wonder if you'd want to expand `:0:` to `:0000:` in each segment. Not sure.

As for the PTR record format, that's a TIL for me.

Since the Go standard library doesn't support either of these operations, I'm curious how often they are actually necessar in practice. But I'll let others chime in.

**Comment by jimmystewpot** [comment]
> I've seen some systems that don't handle the compressed format properly and think it'd be reasonable to add the first method to expand ::, but I would also wonder if you'd want to expand :0: to :0000: in each segment. Not sure.

I agree that the implementation should use the full quad format.

> I'm curious how often they are actually necessar in practice

I am only aware of the full dotted syntax being used in DNS PTR records for IPv6. If you are interested [here](https://tools.ietf.org/html/rfc8501#section-1.2) is an example from an RFC. I am only aware of the expanded quad format being used in enterprise security appliances however I am sure there are other cases I am unaware of. I agree that these are not capabilities that are in high demand. There have been requests to expand on the existing capabilities in the main go std libraries. https://github.com/golang/go/issues/30264 is one example that came up when I started looking.

Thinking further about my initial example and taking your first comment on board would the following make more sense?

```
ip, _ := netaddr.ParseIP("2404:6800:4006:809::200e")
ip.As16Expanded() // 2404:6800:4006:0809:0000:0000:0000:200e
ip.As16ExpandedDotted() // 2.4.0.4.6.8.0.0.4.0.0.6.0.8.0.9.0.0.0.0.0.0.0.0.0.0.0.0.2.0.0.e
```

**Comment by bradfitz** [comment]
Maybe `func (ip IP) StringExpanded() string` method for the first one. I'm not sure we need (or want) the PTR record one. It seems esoteric enough that callers can write it themselves in their calling code: https://play.golang.org/p/_xcPmX4s4bo

```go
func ptr(ip netaddr.IP) string {
	var s strings.Builder
	s.Grow(64)
	for _, b := range ip.As16() {
		fmt.Fprintf(&s, ".%x.%x", b>>4, b&0b1111)
	}
	return s.String()[1:]
}
```

**Comment by jimmystewpot** [comment]
Thanks @bradfitz & @mdlayher  appreciate your responses and feedback.

I'll add the expansion for full quad expansion of IPv6 and submit a PR for review. I'll wait until you remove the warning in the readme incase there are any internal changes. Do you want to close this issue and i'll just reference it in the PR or ?

**Comment by mdlayher** [comment]
@jimmystewpot apologies for the delay, if you'd like to send a PR with `func (ip IP) StringExpanded() string` that seems good to me. We recently landed a big change to move to uint64s internally and I don't suspect there will be a ton more churn at this point as far as the internal structure goes.

We can leave this issue open and close it when your PR is merged.

**Comment by nemith** [comment]
string expanded would fit a use case for me as well.  I had proposed formatter for this in the stdlib but it wouldn't work due to import dependencies, but a simple function would suffice.

https://github.com/golang/go/issues/30264

**Comment by danderson** [comment]
Revisiting this briefly: turns out I need to construct PTR names for IP ranges, and it's just annoying enough to do that it's tempting to add support to netaddr. Something like:

```
// PTR returns the PTR record name for ip.
// e.g. 1.2.3.4 -> 4.3.2.1.in-addr.arpa.
// e.g. fe80::75f1:b7a8:9988:dca8 -> 8.a.c.d.8.8.9.9.8.a.7.b.1.f.5.7.0.8.e.f.ip6.arpa.
func (ip IP) PTR() string

// PTRs returns the PTR record suffixes that fully cover ipr.
// e.g. 1.2.3.0-1.2.3.255 -> [3.2.1.in-addr.arpa.]
// e.g. 1.2.3.0-1.2.4.2 -> [3.2.1.in-addr.arpa. 0.4.2.1.in-addr.arpa. 1.4.2.1.in-addr.arpa. 2.4.2.1.in-addr.arpa.]
// e.g. fe80::/64 -> [0.0.0.0.0.0.0.0.0.0.0.0.0.8.e.f.ip6.arpa.]
func (ipr IPRange) PTRs() []string
func (pfx IPPrefix) PTRs() []string
```

The general idea here is "which DNS suffixes do I need to handle if I want to respond to PTR requests for these IPs?" Maybe that's too specific to live in netaddr, but in particular the logic for "derive the right list of suffixes for a range/prefix" is tricky enough that it'd be lovely to have one good implementation.

Thoughts?

**Comment by jimmystewpot** [comment]
The three use cases that you mention mirror what our personal use patterns look like
- generate PTR's for individual IP addresses
- generate PTR's for all IP addresses within a prefix
- generate PTR's for a subset of a prefix (IP Range).

At this point in time we use the output of To and From on IPRange to loop through and generate the PTR's. Having a dedicated method would be very nice.

**Comment by bradfitz** [comment]
Every new method is something the linker can't remove for many people (once you use https://golang.org/pkg/reflect/#Value.MethodByName anywhere in your program).

So I'm still kinda _meh_ on this like I was in November.

**Comment by nemith** [comment]
PTR addresses aside the original intent was to represent the expanded form of the ipv6 address (used for inserting to databases, files, etc) and not PTR records.

What is the concern with more methods.  Binary size?
