### ISSUE TITLE
Don't parse zones by default

### ISSUE THREAD

**Issue by bradfitz** [inetaf/netaddr#54]
Once we do #53, accepting IPs from the network becomes dangerous, as parsing untrusted IPs with zones causes programs to allocate forever.

We briefly discussed just making all zone parsing very opt-in and not do it by default anywhere.

Does that work for you, @mdlayher? (You're the primary user of zones)

/cc @danderson @crawshaw @josharian

**Comment by mdlayher** [comment]
Assuming the opt in is easy, I'm good with it!

**Comment by bradfitz** [comment]
Actually, with https://github.com/inetaf/netaddr/pull/57 we don't even need to change anything.

**Comment by bradfitz** [comment]
No longer necessary.
