### ISSUE TITLE
change primary branch to "main"

### ISSUE THREAD

**Issue by josharian** [inetaf/netaddr#71]
Objections?

**Comment by danderson** [comment]
I was just thinking that earlier today. I suggest we delay until the current flurry of changes has landed, and do the rename in the quiet period.

**Comment by bradfitz** [comment]
Waiting a ~week sounds good.

**Comment by josharian** [comment]
This is done. Please use branch `main` going forward.

**Comment by danderson** [comment]
PSA, deleting the "master" branch auto-closed all PRs that were set to merge against master. I'm reopening them and repointing them to main.

**Comment by danderson** [comment]
... And by that I mean github won't let me reopen them. But they were both mine anyway, so I'll resend them against main.

**Comment by josharian** [comment]
> PSA, deleting the "master" branch auto-closed all PRs that were set to merge against master. I'm reopening them and repointing them to main.

Blarg. Sorry about that.
