### ISSUE TITLE
Decide which forms of IP addresses to support

### ISSUE THREAD

**Issue by danderson** [inetaf/netaddr#73]
While digging into implementing ParseIP without relying on the stdlib, I found the following representations of IPs that various parsers consider valid:

`192.168.140.255` (classic dotted quad)
`192.168.36095` ("class B" notation, final number encodes 16 bits of the IP)
`192.11046143` ("class A" notation, final number encodes 24 bits of the IP)
`3232271615` (entire IP as a uint32, which I'm facetiously going to call "Class Omega")
`0xc0.0xa8.0x8c.0xff` (dotted quad, with hex numbers)
`0300.0250.0214.0377` (dotted quad, with octal numbers)
`001.002.003.004` (dotted quad, each field is exactly 3 decimal digits, leading zeros not omitted)
`00000001.00000002.00000003.000000004` (same as above, but unlimited leading zeros)

`1111:2222:3333:4444:5555:6666:7777:8888` (fully expanded canonical colon-hex notation)
`1111::8888` (1 or more 16-bit blocks of zeros elided)
`1111::1.2.3.4` (final 32 bits of IPv6 written as IPv4 dotted quad - only a subset of the above nonsense is permitted in the IPv6 notation)
`00000001::00000008` (unlimited number of leading zeros - technically not compliant with RFC grammar, but allegedly accepted fairly widely)

Which of these should we support in netaddr? RFCs don't help us much here. The textual form of IPv6 is somewhat specified, and the "final dotted-quad" format specifies a subset of the above as acceptable, but there is no formal specification of the IPv4 textual form, so it comes down to "what do people use" and "what do parsers understand" - with most of the whackier things seemingly introduced by 4.2BSD and copied around from there, rather than based on some principled belief about the value of those representations.

My opinions:

Obvious yes:
 - IPv4 dotted quad, including the form with leading zeros up to 3 digits total.
 - IPv6 colon-hex, with ::

Leaning yes:
 - IPv4 dotted quad with unlimited number of leading zeros.
 - IPv6 colon-hex with unlimited number of leading zeros (unless RFC explicitly forbids it)

Leaning no:
 - IPv6 with trailing IPv4 dotted quad. Was useful back when transition mechanisms threatened to make ::1.2.3.4 common, but that time no longer exists.
 - IPv4 as a single uint32. This seems to be used accidentally more often than intentionally.

Strong no:
 - Class A/B notation. I've only ever seen them used as curiosities, or by malware to surprise unsuspecting software.
 - Octal dotted-quad notation. Clashes with sensible support of leading zeros, and extremely surprising to unsuspecting users - especially given that windows formats some IPs in 000.000.000.000 form and intends that to be decimal.
 - Hex dotted-quad notation. Slightly less offensive than octal, but I just can't think of a good reason to encourage that sort of nonsense.

/cc @bradfitz @mdlayher @josharian thoughts? Should our parser aim to parse "anything that anyone has ever used to represent IPs" ? Or should we exercise editorial privilege and cut out options we don't think the world should be using?

Will follow up with a survey of what of the above the stdlib accepts.

**Comment by danderson** [comment]
The stdlib net package understands the formats in my "Obvious yes" and "Leaning yes" section, as well as the "IPv6 with trailing IPv4 dotted quad" form from my "Leaning no" section. All the other formats result in a parse error.

**Comment by danderson** [comment]
If it wasn't clear: right now, we implement parity with the stdlib, because we literally delegate ParseIP to it. So unless we decide otherwise, I'm assuming we're sticking to parity with net.ParseIP and not supporting other variations.

**Comment by josharian** [comment]
I would love to move towards a more sane set of strings that count as IPs...but my vote is exact parity with the standard library. The benefits are considerable: no one has to think about the differences when migrating, we avoid security holes from parsers accepting different things, we can use the invariant for fuzzing and regression tests.

**Comment by bradfitz** [comment]
I filed https://github.com/golang/go/issues/43389 for the unlimited zeros in std's ParseIP. (meant to do that when I added that test in 48cf580e974fef8cf06a8bb11a5b2e231e7ed4df)

**Comment by Lewiscowles1986** [comment]
Given https://github.com/golang/go/issues/43389, I had assumed that the PR linked would include a case for the bounds checked IP.

Are you supporting the unbounded representation for BC, or are you open to PR's looking to address?

**Comment by Lewiscowles1986** [comment]
what do you think of the following short-circuit at the beginning of the `ParseIP` method

```
	// https://github.com/golang/go/issues/43389
	// largest supported FE80:0000:0000:0000:0202:B3FF:FE1E:8329 (40-chars)
	if len(s) > 40 {
		return IP{}, fmt.Errorf("Input string representation is more than a full IPv6")
	}
```

Are there cases I've not considered?
Should max length bounds be a separate method altogether so that `ParseIP` retains BC?
In the case it should be another method altogether, does it fit with the broad-goals of this repo?
Does it belong somewhere else?

10MB of zero characters is a very special case. It seems too large to be a network transmitted error. TBH I am unsure the use-case of n-level zero padding. Perhaps it is a trade-off for performance?

**Comment by josharian** [comment]
> what do you think of the following short-circuit at the beginning of the ParseIP method

I think we should only do that if the standard library does that, given the benefits listed above to exactly matching package net. (I'm in favor of upstream doing that, but that's a conversation for a different thread.)

**Comment by danderson** [comment]
Sounds like this bug is done: for parsing, we'll maintain compatibility with the standard library. For String, we maintain a slightly different invariant, which is that the strings we produce will parse back into the same net.IP, but we may pick a different textual representation of the same value.

**Comment by danderson** [comment]
For posterity, that means ParseIP must support:
 - IPv4 dotted decimal, with any number of leading zeros per field
 - IPv6 colon-hex with optional `::`-elided fields, any number of leading zeros per field, and optionally the final 32 bits expressed as IPv4 dotted decimal, with the same behavior as the previous point.
