### ISSUE TITLE
add ParseIPRange, IPRange.String?

### ISSUE THREAD

**Issue by bradfitz** [inetaf/netaddr#85]
I've implemented my own ParseIPRange a few times now. Add to this package?

And corresponding `IPRange.String()` in form `from.String() + "-" + to.String()`?

Objections?

/cc @danderson @mdlayher @josharian

**Comment by josharian** [comment]
SGTM

**Comment by bradfitz** [comment]
e.g. here's one of the existing IPRange parsers: https://github.com/tailscale/tailscale/blob/70f14af21eaa130f0f677d30310951715c9498eb/wgengine/filter/tailcfg.go#L97

There's another in the coordinator server.
