### ISSUE TITLE
proposal: netaddr.Mask type for IP address masking

### ISSUE THREAD

**Issue by mdlayher** [inetaf/netaddr#9]
I was planning to propose netaddr.Prefix, but I think netaddr.Mask is a prerequisite.

I was taking a look at net.IPMask and wondered why it was represented with []byte instead of an integer, and I can only assume it is to support the insanity of IPv4 non-contiguous subnet masks.

I am wondering whether it's even necessary to indicate an IP address family in a mask as I suspect the caller would always know if they're working with IPv4 or IPv6 addresses, so perhaps something as minimal as this would work:

```go
// An IPMask is a CIDR IP address mask length value.
// TODO: consider a struct instead to hide internal representation? Maybe to disallow
// value >128?
type IPMask byte

// IPv4Mask returns the IP mask (in 4-byte form) of the IPv4 mask a.b.c.d. The input
// bytes must contain all leading ones followed by all trailing zeros or
// IPv4Mask will return an error.
func IPv4Mask(a, b, c, d byte) (IPMask, error) {}
```

And then a method to mask IP addresses identical to what stdlib does:

```go
// Mask returns the result of masking the IP address ip with mask.
func (ip IP) Mask(mask IPMask) IP {}
```

**Comment by bradfitz** [comment]
It seems `Contains(IP)` is the actual method most people want, no? I was thinking:

```go
type Network struct {
   IP IP
   Bits int
}

func (n Network) Contains(ip IP) bool { ... }
```

Do we need more than that? Seems like the rest might just be an implementation detail.

**Comment by mdlayher** [comment]
I was considering that, but I actually do need the ability to mask off bits in addresses I don't care about. For example, in CoreRAD, I want to discover all unique /64 subnets attached to an interface:

fe80::1/64 (static)
2001:db8::1/64 (static)
2001:db8::1234/64 (temporary address)

Results in fe80::/64 and 2001:db::/64.

To do this, I have to apply a mask like `ipnet.IP.Mask(ipnet.Mask)` for each of these addresses.

**Comment by danderson** [comment]
Masking is a big one, but can also be implemented as: `ip.Network(bits)`, meaning "turn this IP into a network of this many bits".

I would agree that just a `bits` integer is sufficient. I would definitely argue for _not_ supporting arbitrary bitmasks and just focusing on CIDR. People who need that should feel welcome to convert back to stdlib types and do the masking themselves (do we offer any other "get me the bytes of this address" accessors?)

I might bikeshed over the name: `Network` to me sounds like it's meant to map to a layer2 network (i.e. a thing with a broadcast address that you can run DHCP on). `Prefix` would be the correct CIDR terminology, and be a cleaner mapping for network-type people. But maybe it's worth confusing network-type people in favor of everyone else who won't make that distinction.
